spring.application.name=test-dev

# Port configuration
server.port=${PORT}

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# Security configuration
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA configuration 
spring.jpa.hibernate.ddl-auto=update

# Hibernate dialect for MySQL
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Show SQL statements in the console
spring.jpa.show-sql=true

# Configuration for Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
